// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWFOyrEYll5LfM-7v8H3haFNJi89IteSQ',
    appId: '1:905580913979:web:a0139a162c2ce4c800c31e',
    messagingSenderId: '905580913979',
    projectId: 'satark-d9cc7',
    authDomain: 'satark-d9cc7.firebaseapp.com',
    storageBucket: 'satark-d9cc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsNc4meMW0a7aAyknhy9yORLuezj700E',
    appId: '1:905580913979:android:6d5c9bb03c321d7100c31e',
    messagingSenderId: '905580913979',
    projectId: 'satark-d9cc7',
    storageBucket: 'satark-d9cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmP1FEIs1x8_iTkoDzilDYKEnCqnPq8PM',
    appId: '1:905580913979:ios:87e234334822bfc000c31e',
    messagingSenderId: '905580913979',
    projectId: 'satark-d9cc7',
    storageBucket: 'satark-d9cc7.firebasestorage.app',
    iosBundleId: 'com.example.liveCrimeReporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmP1FEIs1x8_iTkoDzilDYKEnCqnPq8PM',
    appId: '1:905580913979:ios:87e234334822bfc000c31e',
    messagingSenderId: '905580913979',
    projectId: 'satark-d9cc7',
    storageBucket: 'satark-d9cc7.firebasestorage.app',
    iosBundleId: 'com.example.liveCrimeReporter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWFOyrEYll5LfM-7v8H3haFNJi89IteSQ',
    appId: '1:905580913979:web:68906917999aa36600c31e',
    messagingSenderId: '905580913979',
    projectId: 'satark-d9cc7',
    authDomain: 'satark-d9cc7.firebaseapp.com',
    storageBucket: 'satark-d9cc7.firebasestorage.app',
  );
}
